import 'package:qixer/view/utils/const_strings.dart';

var appStrings = {
  ConstString.welcome: ConstString.welcome,
  ConstString.couldntLoadProfile: ConstString.couldntLoadProfile,
  ConstString.browseCategories: ConstString.browseCategories,
  ConstString.allCategories: ConstString.allCategories,
  ConstString.topServices: ConstString.topServices,
  ConstString.recentListed: ConstString.recentListed,
  ConstString.seeAll: ConstString.seeAll,
  ConstString.home: ConstString.home,
  ConstString.orders: ConstString.orders,
  ConstString.save: ConstString.save,
  ConstString.saved: ConstString.saved,
  ConstString.search: ConstString.search,
  ConstString.settings: ConstString.settings,
  ConstString.searchServices: ConstString.searchServices,
  ConstString.date: ConstString.date,
  ConstString.schedule: ConstString.schedule,
  ConstString.billed: ConstString.billed,
  ConstString.myOrders: ConstString.myOrders,
  ConstString.sellerDetails: ConstString.sellerDetails,
  ConstString.name: ConstString.name,
  ConstString.email: ConstString.email,
  ConstString.phone: ConstString.phone,
  ConstString.postCode: ConstString.postCode,
  ConstString.address: ConstString.address,
  ConstString.dateSchedule: ConstString.dateSchedule,
  ConstString.amountDetails: ConstString.amountDetails,
  ConstString.packageFee: ConstString.packageFee,
  ConstString.extraService: ConstString.extraService,
  ConstString.subtotal: ConstString.subtotal,
  ConstString.tax: ConstString.tax,
  ConstString.total: ConstString.total,
  ConstString.paymentStatus: ConstString.paymentStatus,
  ConstString.orderStatus: ConstString.orderStatus,
  ConstString.startsFrom: ConstString.startsFrom,
  ConstString.noResultFound: ConstString.noResultFound,
  ConstString.pendingOrders: ConstString.pendingOrders,
  ConstString.activeOrders: ConstString.activeOrders,
  ConstString.completedOrders: ConstString.completedOrders,
  ConstString.totalOrders: ConstString.totalOrders,
  ConstString.city: ConstString.city,
  ConstString.area: ConstString.area,
  ConstString.country: ConstString.country,
  ConstString.supportTicket: ConstString.supportTicket,
  ConstString.editProfile: ConstString.editProfile,
  ConstString.changePass: ConstString.changePass,
  ConstString.logout: ConstString.logout,
  ConstString.create: ConstString.create,
  ConstString.noTicket: ConstString.noTicket,
  ConstString.allServices: ConstString.allServices,
  ConstString.all: ConstString.all,
  ConstString.highestPrice: ConstString.highestPrice,
  ConstString.lowestPrice: ConstString.lowestPrice,
  ConstString.latestService: ConstString.latestService,
  ConstString.fullName: ConstString.fullName,
  ConstString.plzEnterFullName: ConstString.plzEnterFullName,
  ConstString.about: ConstString.about,
  ConstString.yourAddress: ConstString.yourAddress,
  ConstString.plzEnterAddress: ConstString.plzEnterAddress,
  ConstString.chooseCountry: ConstString.chooseCountry,
  ConstString.chooseCity: ConstString.chooseCity,
  ConstString.chooseArea: ConstString.chooseArea,
  ConstString.serviceName: ConstString.serviceName,
  ConstString.ourPackage: ConstString.plzEnterAddress,
  ConstString.ordersCompleted: ConstString.ordersCompleted,
  ConstString.ratings: ConstString.ratings,
  ConstString.overView: ConstString.overView,
  ConstString.aboutSeller: ConstString.aboutSeller,
  ConstString.review: ConstString.review,
  ConstString.benefitOfPremium: ConstString.benefitOfPremium,
  ConstString.faq: ConstString.faq,
  ConstString.bookAppointment: ConstString.bookAppointment,
  ConstString.personalize: ConstString.personalize,
  ConstString.servicePersonalize: ConstString.servicePersonalize,
  ConstString.next: ConstString.next,
  ConstString.whatsIncluded: ConstString.whatsIncluded,
  ConstString.addExtra: ConstString.addExtra,
  ConstString.benefitPackage: ConstString.benefitPackage,
  ConstString.availableSchedule: ConstString.availableSchedule,
  ConstString.availableTime: ConstString.availableTime,
  ConstString.noScheduleAvailable: ConstString.noScheduleAvailable,
  ConstString.chooseLocation: ConstString.chooseLocation,
  ConstString.bookInfos: ConstString.bookInfos,
  ConstString.bookConfirmation: ConstString.bookConfirmation,
  ConstString.bookDetails: ConstString.bookDetails,
  ConstString.location: ConstString.location,
  ConstString.swipeUp: ConstString.swipeUp,
  ConstString.proceedToPay: ConstString.proceedToPay,
  ConstString.collapse: ConstString.collapse,
  ConstString.appointmentPackService: ConstString.appointmentPackService,
  ConstString.extraServFee: ConstString.extraServFee,
  ConstString.coupon: ConstString.coupon,
  ConstString.couponCode: ConstString.couponCode,
  ConstString.enterCouponCode: ConstString.enterCouponCode,
  ConstString.apply: ConstString.apply,
  ConstString.payment: ConstString.payment,
  ConstString.totalPayable: ConstString.totalPayable,
  ConstString.choosePayMethod: ConstString.choosePayMethod,
  ConstString.chooseImages: ConstString.chooseImages,
  ConstString.chooseImage: ConstString.chooseImage,
  ConstString.iAgreeTerms: ConstString.iAgreeTerms,
  ConstString.paySuccess: ConstString.paySuccess,
  ConstString.areYouSure: ConstString.areYouSure,
  ConstString.cancel: ConstString.cancel,
  ConstString.welcomeBackLogin: ConstString.welcomeBackLogin,
  ConstString.pass: ConstString.pass,
  ConstString.rememberMe: ConstString.rememberMe,
  ConstString.forgotPass: ConstString.forgotPass,
  ConstString.login: ConstString.login,
  ConstString.enterPass: ConstString.enterPass,
  ConstString.dontHaveAccount: "Do not have an account",
  ConstString.register: ConstString.register,
  ConstString.or: ConstString.or,
  ConstString.loginGoogle: ConstString.loginGoogle,
  ConstString.loginFb: ConstString.loginFb,
  ConstString.registerToJoin: ConstString.registerToJoin,
  ConstString.enterFullName: ConstString.enterFullName,
  ConstString.enterUsername: ConstString.enterUsername,
  ConstString.plzEnterName: ConstString.plzEnterName,
  ConstString.enterYourEmail: ConstString.enterYourEmail,
  ConstString.continueTxt: ConstString.continueTxt,
  ConstString.alreadyHaveAccount: ConstString.alreadyHaveAccount,
  ConstString.repeatPass: ConstString.repeatPass,
  ConstString.phoneNumber: ConstString.phoneNumber,
  ConstString.enterPhoneNumber: ConstString.enterPhoneNumber,
  ConstString.resetPass: ConstString.resetPass,
  ConstString.enterEmailToGetInstruction:
      ConstString.enterEmailToGetInstruction,
  ConstString.enterEmail: ConstString.enterEmail,
  ConstString.sendInstructions: ConstString.sendInstructions,
  ConstString.enterFourDigitToEmailVerify:
      ConstString.enterFourDigitToEmailVerify,
  ConstString.enterFourDigitCodeToReset: ConstString.enterFourDigitCodeToReset,
  ConstString.didNotReceive: ConstString.didNotReceive,
  ConstString.sendAgain: ConstString.sendAgain,
  ConstString.somethingWrong: ConstString.somethingWrong,
  ConstString.plzWaitProfileUpdating: ConstString.plzWaitProfileUpdating,
  ConstString.plzEnterEmail: ConstString.plzEnterEmail,
  ConstString.plzEnterPost: ConstString.plzEnterPost,
  ConstString.mustSelectStateArea: ConstString.mustSelectStateArea,
  ConstString.addressRequired: ConstString.addressRequired,
  ConstString.phoneRequired: ConstString.phoneRequired,
  ConstString.updateProfileTakeFewSec: ConstString.updateProfileTakeFewSec,
  ConstString.registerAgreeTerms: ConstString.registerAgreeTerms,
  ConstString.passDidntMatch: ConstString.passDidntMatch,
  ConstString.passMustBeSix: ConstString.passMustBeSix,
  ConstString.haveAnAccount: ConstString.haveAnAccount,
  ConstString.success: ConstString.success,
  ConstString.hiredSuccessful: ConstString.hiredSuccessful,
  ConstString.delete: ConstString.delete,
  ConstString.edit: ConstString.edit,
  ConstString.createJob: ConstString.createJob,
  ConstString.title: ConstString.title,
  ConstString.plzEnterTitle: ConstString.plzEnterTitle,
  ConstString.budget: ConstString.budget,
  ConstString.plzEnterBudget: ConstString.plzEnterBudget,
  ConstString.description: ConstString.description,
  ConstString.endDate: ConstString.endDate,
  ConstString.enterValidBudget: ConstString.enterValidBudget,
  ConstString.offline: ConstString.offline,
  ConstString.online: ConstString.online,
  ConstString.jobReqId: ConstString.jobReqId,
  ConstString.editJob: ConstString.editJob,
  ConstString.attachment: ConstString.attachment,
  ConstString.writeMessage: ConstString.writeMessage,
  ConstString.plzWriteMessageFirst: ConstString.plzWriteMessageFirst,
  ConstString.deadline: ConstString.deadline,
  ConstString.jobRequests: ConstString.jobRequests,
  ConstString.yourOffer: ConstString.yourOffer,
  ConstString.sellerOffer: ConstString.sellerOffer,
  ConstString.noReqFound: ConstString.noReqFound,
  ConstString.viewDetails: ConstString.viewDetails,
  ConstString.conversation: ConstString.conversation,
  ConstString.hireNow: ConstString.hireNow,
  ConstString.onOff: ConstString.onOff,
  ConstString.noJobFound: ConstString.noJobFound,
  ConstString.wallet: ConstString.wallet,
  ConstString.balance: ConstString.balance,
  ConstString.history: ConstString.history,
  ConstString.id: ConstString.id,
  ConstString.gateway: ConstString.gateway,
  ConstString.amount: ConstString.amount,
  ConstString.conversations: ConstString.conversations,
  ConstString.noActiveConversation: ConstString.noActiveConversation,
  ConstString.depositeAmount: ConstString.depositeAmount,
  ConstString.enterDepositeAmount: ConstString.enterDepositeAmount,
  ConstString.orderExtraAccepted: ConstString.orderExtraAccepted,
  ConstString.details: ConstString.details,
  ConstString.time: ConstString.time,
  ConstString.enterName: ConstString.enterName,
  ConstString.enterPostCode: ConstString.enterPostCode,
  ConstString.enterAddress: ConstString.enterAddress,
  ConstString.mustAgreeTerms: ConstString.mustAgreeTerms,
  ConstString.selectLocation: ConstString.selectLocation,
  ConstString.enterNewPass: ConstString.enterNewPass,
  ConstString.newPassDifferent: ConstString.newPassDifferent,
  ConstString.plzEnterPass: ConstString.plzEnterPass,
  ConstString.newPass: ConstString.newPass,
  ConstString.repeatNewPass: ConstString.repeatNewPass,
  ConstString.plzRetypePass: ConstString.plzRetypePass,
  ConstString.retypeNewPass: ConstString.retypeNewPass,
  ConstString.verifyEmail: ConstString.verifyEmail,
  ConstString.signUp: ConstString.signUp,
  ConstString.signIn: ConstString.signIn,
  ConstString.recentJobs: ConstString.recentJobs,
  ConstString.noServiceAvailableInYourArea:
      ConstString.noServiceAvailableInYourArea,
  ConstString.topBooked: ConstString.topBooked,
  ConstString.menu: ConstString.menu,
  ConstString.skip: ConstString.skip,
  ConstString.ok: ConstString.ok,
  ConstString.orderCompleted: ConstString.orderCompleted,
  ConstString.orderCompleteRate: ConstString.orderCompleteRate,
  ConstString.sellerSince: ConstString.sellerSince,
  ConstString.from: ConstString.from,
  'Category': 'Category',
  'Sub Category': 'Sub Category',
  'Ratings': 'Ratings',
  'Sort By': 'Sort By',
  'Write a review': 'Write a review',
  'How was the service?': 'How was the service?',
  'Post review': 'Post review',
  "All Services": "All Services",
  "No service available": "No service available",
  'Reports': 'Reports',
  'Chat with admin': 'Chat with admin',
  'Order id': 'Order id',
  'No Report found': 'No Report found',
  'Write message': 'Write message',
  'Report': 'Report',
  'What went wrong?': 'What went wrong?',
  'Write the issue': 'Write the issue',
  'Submit Report': 'Submit Report',
  'You must write something to submit report':
      'You must write something to submit report',
  'Payment method': 'Payment method',
  'Pay now': 'Pay now',
  'Complete Request': 'Complete Request',
  'Declined': 'Declined',
  'Order completed': 'Order completed',
  'Seller requested to mark this order complete':
      'Seller requested to mark this order complete',
  'Decline': 'Decline',
  'Accept': 'Accept',
  'Decline history': 'Decline history',
  "Decline reason": "Decline reason",
  'Describe why you want to decline the request':
      'Describe why you want to decline the request',
  'You must enter decline reason': 'You must enter decline reason',
  'Extras': 'Extras',
  'Post code': 'Post code',
  'Order Details': 'Order Details',
  'No details found': 'No details found',
  'My Orders': 'My Orders',
  'You can not cancel this order': 'You can not cancel this order',
  "No active order": "No active order",
  'You do not have permission to access this feature':
      'You do not have permission to access this feature',
  "Personal informations": "Personal informations",
  "Enter current password": "Enter current password",
  "Enter your current password": "Enter your current password",
  'Create ticket': 'Create ticket',
  "Priority": "Priority",
  "Order number": "Order number",
  'You do not have any active order': 'You do not have any active order',
  'Please enter ticket title': 'Please enter ticket title',
  "Ticket title": "Ticket title",
  'Please explain your problem': 'Please explain your problem',
  'Support tickets': 'Support tickets',
  "Edit Profile": "Edit Profile",
  'Full name': 'Full name',
  'Phone Number': 'Phone Number',
  'Saved services': 'Saved services',
  "No service saved": "No service saved",
  'No history found': 'No history found',
  'Payment failed but order placed!': 'Payment failed but order placed!',
  'Payment failed but the order is placed. Payment status is pending. You can try to pay again from the orders page':
      'Payment failed but the order is placed. Payment status is pending. You can try to pay again from the orders page',
};
