var appStrings = {
  "welcome": "welcome",
  'Could not load user profile info': 'Could not load user profile info',
  "Browse categories": "Browse categories",
  "All categories": "All categories",
  "Top services": "Top services",
  "Recently listed": "Recently listed",
  "See all": "See all",
  "Home": "Home",
  "Orders": "Orders",
  "Save": "Save",
  "Saved": "Saved",
  "Search": "Search",
  "Settings": "Settings",
  "Search services": "Search services",
  "Date": "Date",
  "Schedule": "Schedule",
  "Billed": "Billed",
  "My orders": "My orders",
  "Seller Details": "Seller Details",
  "Name": "Name",
  "Email": "Email",
  "Phone": "Phone",
  "Post Code": "Post Code",
  "Address": "Address",
  "Date & Schedule": "Date & Schedule",
  "Amount Details": "Amount Details",
  "Package fee": "Package fee",
  "Extra service": "Extra service",
  "Subtotal": "Subtotal",
  "Tax": "Tax",
  "Total": "Total",
  "Payment status": "Payment status",
  "Order Status": "Order Status",
  "Saved Services": "Saved Services",
  "Starts from": "Starts from",
  "No result found": "No result found",
  "Pending orders": "Pending orders",
  "Active orders": "Active orders",
  "Completed orders": "Completed orders",
  "Total orders": "Total orders",
  "City": "City",
  "Area": "Area",
  "Country": "Country",
  "Support ticket": "Support ticket",
  "Edit profile": "Edit profile",
  "Change Password": "Change Password",
  "Logout": "Logout",
  "Create": "Create",
  "No ticket": "No ticket",
  "All services": "All services",
  "All": "All",
  "Highest price": "Highest price",
  "Lowest price": "Lowest price",
  "Latest service": "Latest service",
  "Full Name": "Full Name",
  'Please enter your full name': 'Please enter your full name',
  "About": "About",
  "Your Address": "Your Address",
  'Please enter your address': 'Please enter your address',
  "Choose country": "Choose country",
  "Choose city": "Choose city",
  "Choose Area": "Choose Area",
  "Service Name": "Service Name",
  "Our Package": "Our Package",
  "Orders Completed": "Orders Completed",
  "Seller ratings": "Seller ratings",
  "Overview": "Overview",
  "About Seller": "About Seller",
  "Review": "Review",
  "Benefits of premium Package": "Benefits of premium Package",
  "FAQ": "FAQ",
  "Book appointment": "Book appointment",
  "Personalize": "Personalize",
  "Service personalization": "Service personalization",
  "Next": "Next",
  "What's included": "What's included",
  "Add Extra": "Add Extra",
  "Benefits of the package": "Benefits of the package",
  "Available Schedules": "Available Schedules",
  "Available time": "Available time",
  "No schedule available on this date": "No schedule available on this date",
  "Choose Location": "Choose Location",
  "Booking informations": "Booking informations",
  "Booking Information": "Booking Information",
  "Booking confirmation": "Booking confirmation",
  "Booking Details": "Booking Details",
  "Location": "Location",
  "Swipe up for details": "Swipe up for details",
  "Proceed to payment": "Proceed to payment",
  "Collapse details": "Collapse details",
  "Appointment package service": "Appointment package service",
  "Extra service fee": "Extra service fee",
  "Coupon": "Coupon",
  "Coupon code": "Coupon code",
  "Enter coupon code": "Enter coupon code",
  "Apply": "Apply",
  "Payment": "Payment",
  "Total payable": "Total payable",
  "Choose payment method": "Choose payment method",
  "Choose images": "Choose images",
  'Choose image': 'Choose image',
  "I agree with the terms and conditions":
      "I agree with the terms and conditions",
  "Pay & confirm": "Pay & confirm",
  "Payment successful": "Payment successful",
  "Order status": "Order status",
  "Are you sure": "Are you sure",
  "Cancel": "Cancel",
  "Welcome back! Login": "Welcome back! Login",
  "Password": "Password",
  "Remember me": "Remember me",
  "Forgot Password?": "Forgot Password?",
  "Login": "Login",
  "Enter password": "Enter password",
  "Do not have an account": "Do not have an account",
  "Register": "Register",
  "Or": "Or",
  "Login with google": "Login with google",
  "Login with facebook": "Login with facebook",
  "Register to join us": "Register to join us",
  "Enter your full name": "Enter your full name",
  "Enter your username": "Enter your username",
  'Please enter your username': 'Please enter your username',
  "Enter your email": "Enter your email",
  "Continue": "Continue",
  "Already have an account": "Already have an account",
  "Repeat password": "Repeat password",
  "Phone number": "Phone number",
  'Enter phone number': 'Enter phone number',
  "Reset password": "Reset password",
  "Enter the email you used to create account and we’ll send instruction for restting password":
      "Enter the email you used to create account and we’ll send instruction for restting password",
  "Enter email": "Enter email",
  "Send instructions": "Send instructions",
  "Enter the 4 digit code": "Enter the 4 digit code",
  "Enter the 4 digit code we sent to your email in order to reset password":
      "Enter the 4 digit code we sent to your email in order to reset password",
  "Did not receive": "Didn't receive",
  "Send again": "Send again",
  "Something went wrong": "Something went wrong",
  "Please wait while the profile is updating":
      "Please wait while the profile is updating",
  "Please enter your email": "Please enter your email",
  "Please enter post code": "Please enter post code",
  "You must select a state and area": "You must select a state and area",
  "Address field is required": "Address field is required",
  "Phone field is required": "Phone field is required",
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  "You must agree with the terms and conditions to register":
      "You must agree with the terms and conditions to register",
  "Password did not match": "Password did not match",
  "Password must be at least 6 characters":
      "Password must be at least 6 characters",
  "Have an account": "Have an account",
  "Success": "Success",
  'Hired successfully': 'Hired successfully',
  "Delete": "Delete",
  "Edit": "Edit",
  "Create Job": "Create Job",
  "Title": "Title",
  'Please enter a title': 'Please enter a title',
  "Budget": "Budget",
  "Please enter your budget": "Please enter your budget",
  "Description": "Description",
  "End date": "End date",
  "You must enter a valid budget": "You must enter a valid budget",
  "Offline": "Offline",
  "Online": "Online",
  "Job Request ID": "Job Request ID",
  "Edit job": "Edit job",
  'Attachment': 'Attachment',
  "Write message...": "Write message...",
  "Please write a message first": "Please write a message first",
  "Deadline": "Deadline",
  "Job Requests": "Job Requests",
  "Your offer": "Your offer",
  "Seller offer": "Seller offer",
  'No request found': 'No request found',
  "View details": "View details",
  "Conversation": "Conversation",
  "Hire now": "Hire now",
  "On/Off": "On/Off",
  'No jobs found': 'No jobs found',
  "Wallet": "Wallet",
  "Balance": "Balance",
  "History": "History",
  "ID": "ID",
  "Gateway": "Gateway",
  "Amount": "Amount",
  "Conversations": "Conversations",
  'You do not have any active conversation':
      'You do not have any active conversation',
  "Deposite Amount": "Deposite Amount",
  "Enter deposite amount": "Enter deposite amount",
  "Add extras": "Add extras",
  "Benifits of the Package": "Benifits of the Package",
  'Package Fee': 'Package Fee',
  'Extra Service Fee': 'Extra Service Fee',
  'Order extra accepted': 'Order extra accepted',
  "Details": "Details",
  "Time": "Time",
  "Please enter your name": "Please enter your name",
  'Enter your name': 'Enter your name',
  'Enter your post code': 'Enter your post code',
  'Enter your address': 'Enter your address',
  'I agree with terms and conditions': 'I agree with terms and conditions',
  'You must agree with the terms and conditions to place the order':
      'You must agree with the terms and conditions to place the order',
  'What is included': 'What is included',
  'No shedule available on this date': 'No shedule available on this date',
  'Select Location': 'Select Location',
  "Do not have account?": "Do not have account?",
  "OR": "OR",
  "Login with Google": "Login with Google",
  "Login with Facebook": "Login with Facebook",
  "Enter new password": "Enter new password",
  'Your new password should be different from previously used passwords':
      'Your new password should be different from previously used passwords',
  'Please enter your password': 'Please enter your password',
  'New password': 'New password',
  'Repeat new password': 'Repeat new password',
  'Please retype your password': 'Please retype your password',
  'Retype new password': 'Retype new password',
  'Change password': 'Change password',
  'Verify Email': 'Verify Email',
  'Enter the 4 digit code we sent to to your email in order verify your email':
      'Enter the 4 digit code we sent to to your email in order verify your email',
  'Did not receive?': 'Did not receive?',
  'I agree with the terms and conditons':
      'I agree with the terms and conditons',
  'Sign Up': 'Sign Up',
  'Have an account?': 'Have an account?',
  'Sign in': 'Sign in',
  'Recent jobs': 'Recent jobs',
  'No service available in your area': 'No service available in your area',
  'Top booked services': 'Top booked services',
  'Menu': 'Menu',
  'Skip': 'Skip',
  'Ok': 'Ok',
  'Order Completed': 'Order Completed',
  'Order Completion Rate': 'Order Completion Rate',
  'Seller Since': 'Seller Since',
  'From': 'From',
  "Benefits of the premium package": "Benefits of the premium package",
  'Orders completed': 'Orders completed',
  'Seller Ratings': 'Seller Ratings',
  'Category': 'Category',
  'Sub Category': 'Sub Category',
  'Ratings': 'Ratings',
  'Sort By': 'Sort By',
  'Write a review': 'Write a review',
  'How was the service?': 'How was the service?',
  'Post review': 'Post review',
  "All Services": "All Services",
  "No service available": "No service available",
  'Reports': 'Reports',
  'Chat with admin': 'Chat with admin',
  'Order id': 'Order id',
  'No Report found': 'No Report found',
  'Write message': 'Write message',
  'Report': 'Report',
  'What went wrong?': 'What went wrong?',
  'Write the issue': 'Write the issue',
  'Submit Report': 'Submit Report',
  'You must write something to submit report':
      'You must write something to submit report',
  'Payment method': 'Payment method',
  'Pay now': 'Pay now',
  'Complete Request': 'Complete Request',
  'Declined': 'Declined',
  'Order completed': 'Order completed',
  'Seller requested to mark this order complete':
      'Seller requested to mark this order complete',
  'Decline': 'Decline',
  'Accept': 'Accept',
  'Decline history': 'Decline history',
  "Decline reason": "Decline reason",
  'Describe why you want to decline the request':
      'Describe why you want to decline the request',
  'You must enter decline reason': 'You must enter decline reason',
  'Extras': 'Extras',
  'Post code': 'Post code',
  'Order Details': 'Order Details',
  'No details found': 'No details found',
  'My Orders': 'My Orders',
  'You can not cancel this order': 'You can not cancel this order',
  "No active order": "No active order",
  'You do not have permission to access this feature':
      'You do not have permission to access this feature',
  "Personal informations": "Personal informations",
  "Enter current password": "Enter current password",
  "Enter your current password": "Enter your current password",
  'Create ticket': 'Create ticket',
  "Priority": "Priority",
  "Order number": "Order number",
  'You do not have any active order': 'You do not have any active order',
  'Please enter ticket title': 'Please enter ticket title',
  "Ticket title": "Ticket title",
  'Please explain your problem': 'Please explain your problem',
  'Support tickets': 'Support tickets',
  "Edit Profile": "Edit Profile",
  'Full name': 'Full name',
  'Phone Number': 'Phone Number',
  'Saved services': 'Saved services',
  "No service saved": "No service saved",
  "Payment Status": "Payment Status",
  'No history found': 'No history found',
  'Payment failed but order placed!': 'Payment failed but order placed!',
  'Payment failed but the order is placed. Payment status is pending. You can try to pay again from the orders page':
      'Payment failed but the order is placed. Payment status is pending. You can try to pay again from the orders page',
};
