import 'package:qixer/view/utils/const_strings.dart';

var appStrings = {
  ConstString.welcome: ConstString.welcome,
  ConstString.couldntLoadProfile: ConstString.couldntLoadProfile,
  ConstString.browseCategories: ConstString.browseCategories,
  ConstString.allCategories: ConstString.allCategories,
  ConstString.topServices: ConstString.topServices,
  ConstString.recentListed: ConstString.recentListed,
  ConstString.seeAll: ConstString.seeAll,
  ConstString.home: ConstString.home,
  ConstString.orders: ConstString.orders,
  ConstString.save: ConstString.save,
  ConstString.saved: ConstString.saved,
  ConstString.search: ConstString.search,
  ConstString.settings: ConstString.settings,
  ConstString.searchServices: ConstString.searchServices,
  ConstString.date: ConstString.date,
  ConstString.schedule: ConstString.schedule,
  ConstString.billed: ConstString.billed,
  ConstString.myOrders: ConstString.myOrders,
  ConstString.sellerDetails: ConstString.sellerDetails,
  ConstString.name: ConstString.name,
  ConstString.email: ConstString.email,
  ConstString.phone: ConstString.phone,
  ConstString.postCode: ConstString.postCode,
  ConstString.address: ConstString.address,
  ConstString.dateSchedule: ConstString.dateSchedule,
  ConstString.amountDetails: ConstString.amountDetails,
  ConstString.packageFee: ConstString.packageFee,
  ConstString.extraService: ConstString.extraService,
  ConstString.subtotal: ConstString.subtotal,
  ConstString.tax: ConstString.tax,
  ConstString.total: ConstString.total,
  ConstString.paymentStatus: ConstString.paymentStatus,
  ConstString.orderStatus: ConstString.orderStatus,
  ConstString.startsFrom: ConstString.startsFrom,
  ConstString.noResultFound: ConstString.noResultFound,
  ConstString.pendingOrders: ConstString.pendingOrders,
  ConstString.activeOrders: ConstString.activeOrders,
  ConstString.completedOrders: ConstString.completedOrders,
  ConstString.totalOrders: ConstString.totalOrders,
  ConstString.city: ConstString.city,
  ConstString.area: ConstString.area,
  ConstString.country: ConstString.country,
  ConstString.supportTicket: ConstString.supportTicket,
  ConstString.editProfile: ConstString.editProfile,
  ConstString.changePass: ConstString.changePass,
  ConstString.logout: ConstString.logout,
  ConstString.create: ConstString.create,
  ConstString.noTicket: ConstString.noTicket,
  ConstString.allServices: ConstString.allServices,
  ConstString.all: ConstString.all,
  ConstString.highestPrice: ConstString.highestPrice,
  ConstString.lowestPrice: ConstString.lowestPrice,
  ConstString.latestService: ConstString.latestService,
  ConstString.fullName: ConstString.fullName,
  ConstString.plzEnterFullName: ConstString.plzEnterFullName,
  ConstString.about: ConstString.about,
  ConstString.yourAddress: ConstString.yourAddress,
  ConstString.plzEnterAddress: ConstString.plzEnterAddress,
  ConstString.chooseCountry: ConstString.chooseCountry,
  ConstString.chooseCity: ConstString.chooseCity,
  ConstString.chooseArea: ConstString.chooseArea,
  ConstString.serviceName: ConstString.serviceName,
  ConstString.ourPackage: ConstString.plzEnterAddress,
  ConstString.ordersCompleted: ConstString.ordersCompleted,
  ConstString.ratings: ConstString.ratings,
  ConstString.overView: ConstString.overView,
  ConstString.aboutSeller: ConstString.aboutSeller,
  ConstString.review: ConstString.review,
  ConstString.benefitOfPremium: ConstString.benefitOfPremium,
  ConstString.faq: ConstString.faq,
  ConstString.bookAppointment: ConstString.bookAppointment,
  ConstString.personalize: ConstString.personalize,
  ConstString.servicePersonalize: ConstString.servicePersonalize,
  ConstString.next: ConstString.next,
  ConstString.whatsIncluded: ConstString.whatsIncluded,
  ConstString.addExtra: ConstString.addExtra,
  ConstString.benefitPackage: ConstString.benefitPackage,
  ConstString.availableSchedule: ConstString.availableSchedule,
  ConstString.availableTime: ConstString.availableTime,
  ConstString.noScheduleAvailable: ConstString.noScheduleAvailable,
  ConstString.chooseLocation: ConstString.chooseLocation,
  ConstString.bookInfos: ConstString.bookInfos,
  ConstString.bookConfirmation: ConstString.bookConfirmation,
  ConstString.bookDetails: ConstString.bookDetails,
  ConstString.location: ConstString.location,
  ConstString.swipeUp: ConstString.swipeUp,
  ConstString.proceedToPay: ConstString.proceedToPay,
  ConstString.collapse: ConstString.collapse,
  ConstString.appointmentPackService: ConstString.appointmentPackService,
  ConstString.extraServFee: ConstString.extraServFee,
  ConstString.coupon: ConstString.coupon,
  ConstString.couponCode: ConstString.couponCode,
  ConstString.enterCouponCode: ConstString.enterCouponCode,
  ConstString.apply: ConstString.apply,
  ConstString.payment: ConstString.payment,
  ConstString.totalPayable: ConstString.totalPayable,
  ConstString.choosePayMethod: ConstString.choosePayMethod,
  ConstString.chooseImages: ConstString.chooseImages,
  ConstString.chooseImage: ConstString.chooseImage,
  ConstString.iAgreeTerms: ConstString.iAgreeTerms,
  ConstString.paySuccess: ConstString.paySuccess,
  ConstString.areYouSure: ConstString.areYouSure,
  ConstString.cancel: ConstString.cancel,
  ConstString.welcomeBackLogin: ConstString.welcomeBackLogin,
  ConstString.pass: ConstString.pass,
  ConstString.rememberMe: ConstString.rememberMe,
  ConstString.forgotPass: ConstString.forgotPass,
  ConstString.login: ConstString.login,
  ConstString.enterPass: ConstString.enterPass,
  ConstString.dontHaveAccount: "Do not have an account",
  ConstString.register: ConstString.register,
  ConstString.or: ConstString.or,
  ConstString.loginGoogle: ConstString.loginGoogle,
  ConstString.loginFb: ConstString.loginFb,
  ConstString.registerToJoin: ConstString.registerToJoin,
  ConstString.enterFullName: ConstString.enterFullName,
  ConstString.enterUsername: ConstString.enterUsername,
  ConstString.plzEnterName: ConstString.plzEnterName,
  ConstString.enterYourEmail: ConstString.enterYourEmail,
  ConstString.continueTxt: ConstString.continueTxt,
  ConstString.alreadyHaveAccount: ConstString.alreadyHaveAccount,
  ConstString.repeatPass: ConstString.repeatPass,
  ConstString.phoneNumber: ConstString.phoneNumber,
  ConstString.enterPhoneNumber: ConstString.enterPhoneNumber,
  ConstString.resetPass: ConstString.resetPass,
  ConstString.enterEmailToGetInstruction:
      ConstString.enterEmailToGetInstruction,
  ConstString.enterEmail: ConstString.enterEmail,
  ConstString.sendInstructions: ConstString.sendInstructions,
  ConstString.enterFourDigitToEmailVerify:
      ConstString.enterFourDigitToEmailVerify,
  ConstString.enterFourDigitCodeToReset: ConstString.enterFourDigitCodeToReset,
  ConstString.didNotReceive: ConstString.didNotReceive,
  ConstString.sendAgain: ConstString.sendAgain,
  "Something went wrong": "Something went wrong",
  "Please wait while the profile is updating":
      "Please wait while the profile is updating",
  "Please enter your email": "Please enter your email",
  "Please enter post code": "Please enter post code",
  "You must select a state and area": "You must select a state and area",
  "Address field is required": "Address field is required",
  "Phone field is required": "Phone field is required",
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  "You must agree with the terms and conditions to register":
      "You must agree with the terms and conditions to register",
  "Password did not match": "Password did not match",
  "Password must be at least 6 characters":
      "Password must be at least 6 characters",
  "Have an account": "Have an account",
  "Success": "Success",
  'Hired successfully': 'Hired successfully',
  "Delete": "Delete",
  "Edit": "Edit",
  "Create Job": "Create Job",
  "Title": "Title",
  'Please enter a title': 'Please enter a title',
  "Budget": "Budget",
  "Please enter your budget": "Please enter your budget",
  "Description": "Description",
  "End date": "End date",
  "You must enter a valid budget": "You must enter a valid budget",
  "Offline": "Offline",
  "Online": "Online",
  "Job Request ID": "Job Request ID",
  "Edit job": "Edit job",
  'Attachment': 'Attachment',
  "Write message...": "Write message...",
  "Please write a message first": "Please write a message first",
  "Deadline": "Deadline",
  "Job Requests": "Job Requests",
  "Your offer": "Your offer",
  "Seller offer": "Seller offer",
  'No request found': 'No request found',
  "View details": "View details",
  "Conversation": "Conversation",
  "Hire now": "Hire now",
  "On/Off": "On/Off",
  'No jobs found': 'No jobs found',
  "Wallet": "Wallet",
  "Balance": "Balance",
  "History": "History",
  "ID": "ID",
  "Gateway": "Gateway",
  "Amount": "Amount",
  "Conversations": "Conversations",
  'You do not have any active conversation':
      'You do not have any active conversation',
  "Deposite Amount": "Deposite Amount",
  "Enter deposite amount": "Enter deposite amount",
  "Add extras": "Add extras",
  "Benifits of the Package": "Benifits of the Package",
  'Package Fee': 'Package Fee',
  'Extra Service Fee': 'Extra Service Fee',
  'Order extra accepted': 'Order extra accepted',
  "Details": "Details",
  "Time": "Time",
  "Please enter your name": "Please enter your name",
  'Enter your name': 'Enter your name',
  'Enter your post code': 'Enter your post code',
  'Enter your address': 'Enter your address',
  'I agree with terms and conditions': 'I agree with terms and conditions',
  'You must agree with the terms and conditions to place the order':
      'You must agree with the terms and conditions to place the order',
  'What is included': 'What is included',
  'No shedule available on this date': 'No shedule available on this date',
  'Select Location': 'Select Location',
  "Do not have account?": "Do not have account?",
  "OR": "OR",
  "Login with Google": "Login with Google",
  "Login with Facebook": "Login with Facebook",
  "Enter new password": "Enter new password",
  'Your new password should be different from previously used passwords':
      'Your new password should be different from previously used passwords',
  'Please enter your password': 'Please enter your password',
  'New password': 'New password',
  'Repeat new password': 'Repeat new password',
  'Please retype your password': 'Please retype your password',
  'Retype new password': 'Retype new password',
  'Change password': 'Change password',
  'Verify Email': 'Verify Email',
  'Enter the 4 digit code we sent to to your email in order verify your email':
      'Enter the 4 digit code we sent to to your email in order verify your email',
  'Did not receive?': 'Did not receive?',
  'I agree with the terms and conditons':
      'I agree with the terms and conditons',
  'Sign Up': 'Sign Up',
  'Have an account?': 'Have an account?',
  'Sign in': 'Sign in',
  'Recent jobs': 'Recent jobs',
  'No service available in your area': 'No service available in your area',
  'Top booked services': 'Top booked services',
  'Menu': 'Menu',
  'Skip': 'Skip',
  'Ok': 'Ok',
  'Order Completed': 'Order Completed',
  'Order Completion Rate': 'Order Completion Rate',
  'Seller Since': 'Seller Since',
  'From': 'From',
  "Benefits of the premium package": "Benefits of the premium package",
  'Orders completed': 'Orders completed',
  'Category': 'Category',
  'Sub Category': 'Sub Category',
  'Ratings': 'Ratings',
  'Sort By': 'Sort By',
  'Write a review': 'Write a review',
  'How was the service?': 'How was the service?',
  'Post review': 'Post review',
  "All Services": "All Services",
  "No service available": "No service available",
  'Reports': 'Reports',
  'Chat with admin': 'Chat with admin',
  'Order id': 'Order id',
  'No Report found': 'No Report found',
  'Write message': 'Write message',
  'Report': 'Report',
  'What went wrong?': 'What went wrong?',
  'Write the issue': 'Write the issue',
  'Submit Report': 'Submit Report',
  'You must write something to submit report':
      'You must write something to submit report',
  'Payment method': 'Payment method',
  'Pay now': 'Pay now',
  'Complete Request': 'Complete Request',
  'Declined': 'Declined',
  'Order completed': 'Order completed',
  'Seller requested to mark this order complete':
      'Seller requested to mark this order complete',
  'Decline': 'Decline',
  'Accept': 'Accept',
  'Decline history': 'Decline history',
  "Decline reason": "Decline reason",
  'Describe why you want to decline the request':
      'Describe why you want to decline the request',
  'You must enter decline reason': 'You must enter decline reason',
  'Extras': 'Extras',
  'Post code': 'Post code',
  'Order Details': 'Order Details',
  'No details found': 'No details found',
  'My Orders': 'My Orders',
  'You can not cancel this order': 'You can not cancel this order',
  "No active order": "No active order",
  'You do not have permission to access this feature':
      'You do not have permission to access this feature',
  "Personal informations": "Personal informations",
  "Enter current password": "Enter current password",
  "Enter your current password": "Enter your current password",
  'Create ticket': 'Create ticket',
  "Priority": "Priority",
  "Order number": "Order number",
  'You do not have any active order': 'You do not have any active order',
  'Please enter ticket title': 'Please enter ticket title',
  "Ticket title": "Ticket title",
  'Please explain your problem': 'Please explain your problem',
  'Support tickets': 'Support tickets',
  "Edit Profile": "Edit Profile",
  'Full name': 'Full name',
  'Phone Number': 'Phone Number',
  'Saved services': 'Saved services',
  "No service saved": "No service saved",
  'No history found': 'No history found',
  'Payment failed but order placed!': 'Payment failed but order placed!',
  'Payment failed but the order is placed. Payment status is pending. You can try to pay again from the orders page':
      'Payment failed but the order is placed. Payment status is pending. You can try to pay again from the orders page',
};
